### ISSUE TITLE
Were you able to reproduce it?

### ISSUE THREAD

**Issue by bruAristimunha** [matt-houk/MB3DCNN#1]
A Multi-Branch 3D Convolutional Neural Network for EEG-Based Motor Imagery Classification

**Comment by matt-houk** [comment]
I never had success in replicating the success seen in the paper. I have since left academia and transitioned to working in industry. Personally I suspect the original paper either did not completely document their work or had some overfitting occurring in testing.

**Comment by bruAristimunha** [comment]
Ok got it, thank you so much for your answers
